# Generated by Django 4.2.3 on 2023-07-30 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_avatar_alter_customuser_telegram'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='chat_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='telegram_chat_id'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='telegram',
            field=models.CharField(max_length=50, unique=True, verbose_name='telegram'),
        ),
    ]
