version: '3'

services:

  db:
    image: postgres
    container_name: db_app
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: drf_habits
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: app_container
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - '8000:8000'
    depends_on:
      - db
      - redis
    volumes:
      - ./.env:/app/.env

  redis:
    image: redis:7.0.2-alpine
    container_name: redis_app
    command: redis-server --save 20 1 --loglevel warning
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

  celery:
    build: .
    container_name: celery_app
    command: celery -A config worker -l INFO --loglevel warning
    volumes:
      - celery_data:/app
    depends_on:
      - redis

  celery-beat:
    build: .
    container_name: celery_beat_app
    command: celery -A config beat -l info -S django --loglevel warning
    volumes:
      - celery_beat_data:/app
    depends_on:
      - redis
      - celery

volumes:
  postgres_data:
  redis_data:
  celery_beat_data:
  celery_data:
