# Generated by Django 4.2.3 on 2023-07-29 13:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='habit_name')),
                ('action', models.TextField(blank=True, null=True, verbose_name='action_description')),
                ('action_time', models.DateTimeField(verbose_name='action_time')),
                ('action_place', models.CharField(max_length=50, verbose_name='action_place')),
                ('duration', models.DurationField(verbose_name='habit_duration')),
                ('regularity', models.CharField(choices=[('daily', 'Daily'), ('twice_a_week', 'Twice a week'), ('weekly', 'Weekly')], default='daily', max_length=13, verbose_name='habit_regularity')),
                ('is_public', models.BooleanField(default=False, verbose_name='is_habit_public')),
                ('has_auxiliary_habits', models.BooleanField(default=False, verbose_name='has_auxiliary_habits')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Main habit',
                'verbose_name_plural': 'Main habits',
            },
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='reward_name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='reward_description')),
                ('resources', models.CharField(blank=True, null=True, verbose_name='needed_resources')),
                ('main_habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='habit_reward', to='habits.habit', verbose_name='habit_reward')),
            ],
        ),
        migrations.CreateModel(
            name='AuxiliaryHabit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='auxiliary_habit_name')),
                ('action', models.TextField(blank=True, null=True, verbose_name='auxiliary_action_description')),
                ('action_time', models.DateTimeField(blank=True, null=True, verbose_name='auxiliary_action_time')),
                ('action_place', models.CharField(blank=True, max_length=50, null=True, verbose_name='auxiliary_action_place')),
                ('duration', models.DurationField(blank=True, null=True, verbose_name='auxiliary_habit_duration')),
                ('is_public', models.BooleanField(default=False, verbose_name='is_auxiliary_habit_public')),
                ('main_habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_habit', to='habits.habit', verbose_name='main_habit')),
            ],
            options={
                'verbose_name': 'Auxiliary habit',
                'verbose_name_plural': 'Auxiliary habits',
            },
        ),
    ]
