# Generated by Django 4.2.3 on 2023-07-29 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='has_auxiliary_habits',
        ),
    ]
