# Generated by Django 4.2.3 on 2023-07-30 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0005_alter_auxiliaryhabit_action_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='regularity',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('twice_a_week_MT', 'Twice a week (Mon + Thu)'), ('twice_a_week_TF', 'Twice a week (Tue + Fri)'), ('three_times_a_week_MWF', 'Three times a week (Mon + Wed + Fri)'), ('three_times_a_week_TTS', 'Three times a week (Tue + Thu + Sat)'), ('on_weekdays', 'From Monday to Friday'), ('on_weekends', 'From Saturday to Sunday')], default='daily', max_length=23, verbose_name='habit_regularity'),
        ),
    ]
