# Generated by Django 4.2.3 on 2023-07-30 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0006_alter_habit_regularity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='regularity',
            field=models.CharField(choices=[('daily', 'Daily'), ('twice_a_week_MT', 'Twice a week (Mon + Thu)'), ('twice_a_week_TF', 'Twice a week (Tue + Fri)'), ('twice_a_week_WS', 'Twice a week (Wed + Sat)'), ('three_times_a_week_MWF', 'Three times a week (Mon + Wed + Fri)'), ('three_times_a_week_TTS', 'Three times a week (Tue + Thu + Sat)'), ('three_times_a_week_WFS', 'Three times a week (Wed + Fri + Sun)'), ('on_weekdays', 'From Monday to Friday'), ('on_weekends', 'From Saturday to Sunday'), ('each_mon', 'Every Monday'), ('each_tue', 'Every Tuesday'), ('each_wed', 'Every Wednesday'), ('each_thu', 'Every Thursday'), ('each_fri', 'Every Friday'), ('each_sat', 'Every Saturday'), ('each_sun', 'Every Sunday')], default='daily', max_length=23, verbose_name='habit_regularity'),
        ),
    ]
