# Generated by Django 4.2.3 on 2023-08-01 11:22

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0008_habit_days_of_week_alter_habit_regularity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='days_of_week',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('mon', 'Every Monday'), ('tue', 'Every Tuesday'), ('wed', 'Every Wednesday'), ('thu', 'Every Thursday'), ('fri', 'Every Friday'), ('sat', 'Every Saturday'), ('sun', 'Every Sunday')], max_length=23, null=True, verbose_name='days_of_week'),
        ),
    ]
