# Generated by Django 4.2.3 on 2023-08-01 12:06

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0009_alter_habit_days_of_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='days_of_week',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('1', 'Every Monday'), ('2', 'Every Tuesday'), ('3', 'Every Wednesday'), ('4', 'Every Thursday'), ('5', 'Every Friday'), ('6', 'Every Saturday'), ('7', 'Every Sunday')], max_length=23, null=True, verbose_name='days_of_week'),
        ),
    ]
