# Generated by Django 4.2.3 on 2023-08-02 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0010_alter_habit_days_of_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auxiliaryhabit',
            name='main_habit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auxiliary_habit', to='habits.habit', verbose_name='main_habit'),
        ),
    ]
