# Generated by Django 4.2.3 on 2023-08-02 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0011_alter_auxiliaryhabit_main_habit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reward',
            name='main_habit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habit_reward', to='habits.habit', verbose_name='habit_reward'),
        ),
    ]
