# Generated by Django 4.2.3 on 2023-08-02 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0012_alter_reward_main_habit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auxiliaryhabit',
            name='main_habit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auxiliary_habit', to='habits.habit', verbose_name='main_habit'),
        ),
        migrations.AlterField(
            model_name='reward',
            name='main_habit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='habit_reward', to='habits.habit', verbose_name='habit_reward'),
        ),
    ]
